name: Build wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools

      - name: Download source from pip
        run: |
          curl -L -o quickfix.zip https://raw.githubusercontent.com/kazcfz/QuickFIX-prebuilt-wheel/main/quickfix-1.15.1.zip

      - name: Extract source
        run: |
          mkdir -p src
          unzip quickfix.zip -d src

      - name: Build wheel
        run: |
          cd src/quickfix*
          python -m build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheel
          path: src/*/dist/*.whl